#-----------------------------------------------------
#--  Génération de configuration de switch tp-link
#--  ma logique est de définir les vlans sur les ports,
#--  tp-link, fait le contraire
#--  
#--   structure du fichier json
#--  {
#--      "vlans": tableau des vlans
#--      [
#--         {
#--             "num": numéro du port,
#--             "name": num du vlan
#--         }
#--      ],
#--      "ports": tableau des ports
#--      [
#--          {
#--             "num": numero du port, 
#--             "tagged": tableau des vlans sur ce port,
#--             [
#--                 numero du vlan
#--             ],
#--             "untagged": id du vlan, 1 si absent
#--          },
#--      ]
#--  }
#--  
#--  
#-----------------------------------------------------


from io import TextIOWrapper
import ipaddress
import json
from datetime import datetime
import commun


f:TextIOWrapper=None


def main():
    descriptorFn = commun.getArgv("-process", '/home/oec/DEV/Mikrotik/out/tplink.json')
    if ( len(descriptorFn) == 0 ):
        print("-process is mandatory")
        return
    fn = commun.getArgv("-toFile", '/home/oec/DEV/Mikrotik/out/tplink.txt')
    if ( len(fn) == 0 ):
        print("-toFile is mandatory")
        return

    descriptor = commun.dataLoad(descriptorFn)
    if ( len(descriptor) == 0 ):
        print("file %s is empty" % (descriptorFn) )
        return

    j = json.loads(descriptor)

    # vlan names
    vlanName={}
    # liste des ports par vlan
    vlansPorts={} 
    # pvid liste des ports par vlan
    vlansPvid={}
    # liste des ports 
    ports=[]

    for vlansTag in j["vlans"]:
        vlanId = vlansTag["num"]
        if vlanId in vlanName:
            print("vlan %d already defined in vlans, skipping" % (vlanId) )
        else:
            vlanName[vlanId] = vlansTag["name"]

    for portTag in j["ports"]:
        taggedVlanList = portTag.get("tagged", [])
        port = portTag["num"]
        if port in ports:
            print("port %d already defined in ports, skipping" % (port) )
        else:
            ports.append(port)
            # liste des ports pour un vlan untagged
            vlanUntagged = portTag.get("untagged", 1)
            value = vlansPvid.get(vlanUntagged, [])
            value.append(port)
            vlansPvid[vlanUntagged] = value
            # liste des ports pour un vlan tagged
            for tag in taggedVlanList:
                if tag in vlanName:
                    value = vlansPorts.get(tag, [])
                    value.append(port)
                    vlansPorts[tag] = value
                else:
                    print("vlan %d not defined in vlans for port %d, skipping" % (tag, port) )
    

    global f
    f = open(fn, 'w')

    write(  '#######################################################################################')
    write(  '# configuration generated by ohmi')
    write(  '#     script:makeTpLinkVlan.py')
    write( ('#     Source: %s' % (descriptorFn) ) )
    write( ('#     on: %s' % (datetime.now().strftime("%Y/%m/%d %H:%M:%S") ) ) )
    write(  '#######################################################################################')
    write( "" )

    write(  '###############')
    write(  "# 802.1Q VLAN")
    write(  '###############')
    write( "" )
    for vlanId, name in vlanName.items():
        write("  vlan : %d name: %s" % (vlanId, name) )
        tmp=""
        for port in vlansPorts[vlanId]:
            tmp = tmp + ' ' + str(port) + ','
        write("    tagged : %s" % (tmp))
        tmp=""
        if vlanId in vlansPvid:
            for port in vlansPvid[vlanId]:
                # tagged est prioritaire si présent dans les 2 listes
                if not port in vlansPorts[vlanId]:
                    tmp = tmp + ' ' + str(port) + ','
            if len(tmp) > 0:
                write("    untagged : %s" % (tmp))
        write( "" )
    
    write( "" )
    write(  '#######################')
    write(  "# 802.1Q PVID setting")
    write(  '#######################')
    write( "" )
    for vlanId, portList in vlansPvid.items():
        write("  pvid : %d" % (vlanId) )
        tmp=""
        for port in portList:
            tmp = tmp + ' ' + str(port) + ','
        write("    ports : %s" % (tmp))
        write( "" )


    f.close()


def write(s:str)->None:
    f.write('%s\n' % (s) )



main()
